# Generated by Django 5.1.2 on 2025-02-25 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anonymousprivatemessage',
            old_name='receiver',
            new_name='recipient',
        ),
    ]
