# Generated by Django 5.1.2 on 2025-02-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='created_at',
        ),
        migrations.AddField(
            model_name='professional',
            name='available_times',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='professional',
            name='contact_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='professional',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
