# Generated by Django 5.1.2 on 2025-02-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedcourse',
            name='date_completed',
        ),
        migrations.RemoveField(
            model_name='completedcourse',
            name='user',
        ),
        migrations.AddField(
            model_name='completedcourse',
            name='completion_percentage',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='completedcourse',
            name='description',
            field=models.TextField(default='No description provided.'),
        ),
    ]
