# Generated by Django 5.1.2 on 2025-02-13 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_completedcourse_date_completed_and_more'),
    ]

    operations = [
    ]
