# Generated by Django 5.1.2 on 2025-02-19 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_professional_user_delete_professionalprofile'),
    ]

    operations = [
    ]
