# Generated by Django 5.1.2 on 2025-02-19 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20250220_0014'),
    ]

    operations = [
    ]
